# 03 Follow-ups

## Setup

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import os
os.environ['GE_DRIVE_ROOT'] = '/content/drive/MyDrive/hypothesaes_goemotions'
REPO_URL = 'https://github.com/vankadaruvijayberk/HypotheSAEs.git'
REPO_DIR = '/content/HypotheSAEs'

!rm -rf {REPO_DIR}   # always take the pushed version

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Install

In [2]:
import os, subprocess
if not os.path.isdir(REPO_DIR):
    subprocess.run(['git', 'clone', '--depth', '1', REPO_URL, REPO_DIR], check=True)

!pip install -q -e {REPO_DIR}
!pip install -q -U datasets sentence-transformers transformers scikit-learn statsmodels "numpy<2.0.0"

# vLLM alone, so it resolves its own CUDA deps and a failure here cannot take out the
# rest of the environment (the annotator swap falls back to cached annotations)
!pip install -q -U vllm
!pip uninstall -y -q torchcodec

import sys, importlib
for p in (REPO_DIR, os.path.join(REPO_DIR, 'goemotions')):
    if p not in sys.path:
        sys.path.insert(0, p)
importlib.invalidate_caches()
import importlib.util
print('vllm importable:', importlib.util.find_spec('vllm') is not None)

  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for hypothesaes (pyproject.toml) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
vllm 0.26.0 requires torchcodec>=0.14, which is not installed.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.0 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.0 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.0 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.0 which is incompatible.
vllm importable: True

## Imports

In [3]:
import numpy as np
import pandas as pd
from scipy.stats import pearsonr, spearmanr
import ge_pipeline as ge
from hypothesaes.embedding import get_local_embeddings
from hypothesaes.annotate import annotate_texts_with_concepts
ge.set_seed()
ge.redirect_annotation_cache()
ge.fix_cuda_libs()
print('free VRAM (GB):', ge.gpu_free_gb())

cudart: ['libcudart.so.12', 'libcudart.so.13'] | nvidia lib dirs: 16
free VRAM (GB): 14.6

## Load Heldout and Hypotheses

In [4]:
ds, NAMES = ge.load_goemotions()
test_texts = list(ds['test']['text'])
test_targets = ge.build_targets(ds['test']['labels'], NAMES)

interp = ge.read_json('06_interpretations')
evaluation = ge.read_json('07_evaluation')
hidx = evaluation['heldout_indices']            # same rows notebook 02 annotated
held_texts = [test_texts[i] for i in hidx]
held_targets = {t: test_targets[t][hidx] for t in test_targets}

selected = {t: [int(n) for n in v] for t, v in interp['selected'].items()}
neuron2hyp = {int(k): v['interpretation'] for k, v in interp['best'].items() if v['interpretation']}
union_hyps = sorted(set(neuron2hyp.values()))
print('heldout:', len(held_texts), '| hypotheses:', len(union_hyps))

README.md:   0%|          | 0.00/9.40k [00:00<?, ?B/s]

simplified/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 2.77MB

simplified/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

simplified/validation-00000-of-00001.par(…): reconstructing file:   0%|          |  0.00B /  350kB

simplified/validation-00000-of-00001.par(…): downloading bytes:           |  0.00B

simplified/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  347kB

simplified/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/43410 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/5426 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/5427 [00:00<?, ? examples/s]

heldout: 2000 | hypotheses: 64

## Cached Annotations

In [5]:
missing = ge.annotation_cache_missing('goemotions_heldout', union_hyps, held_texts)
assert missing == 0, f'{missing} heldout annotations missing; rerun notebook 02'

llm = annotate_texts_with_concepts(texts=held_texts, concepts=union_hyps, model='Qwen/Qwen3-1.7B',
                                   cache_name='goemotions_heldout', n_workers=1,
                                   use_cache_only=True, uncached_value=0, max_words_per_example=64)
prev = pd.Series({h: float(llm[h].mean()) for h in union_hyps})
print('hypotheses with zero variance on heldout:', int((prev == 0).sum() + (prev == 1).sum()))
prev.describe()

Found 128000 cached items; mapped 0 uncached items to 0
hypotheses with zero variance on heldout: 0

count    64.000000
mean      0.117031
std       0.169084
min       0.000500
25%       0.023250
50%       0.054000
75%       0.122125
max       0.826500
dtype: float64

## Rescore Main Evaluation

In [6]:
# score_hypotheses fits a Logit on the annotation matrix; a hypothesis the annotator
# never fires on is constant, collinear with the intercept -> singular matrix, inf, NaN R2.
stable, dropped_all = {}, []
for t, neurons in selected.items():
    hyps = sorted({neuron2hyp[n] for n in neurons if n in neuron2hyp})
    if len(hyps) < 2:
        continue
    m, df, dropped = ge.score_hypotheses_stable({h: llm[h] for h in hyps},
                                                y_true=held_targets[t].astype(float))
    dropped_all += [dict(d, target=t) for d in dropped]
    if m is None:
        stable[t] = None
        continue
    stable[t] = {'auroc': m.get('auroc'), 'r2': m.get('r2'),
                 'significant': m['Significant'][0], 'n_hyp': m['Significant'][1],
                 'n_dropped': len(dropped)}
ge.log_json('12_evaluation_stable', {'per_target': stable, 'dropped': dropped_all})
print('dropped (zero-variance / duplicate):', len(dropped_all))
pd.DataFrame(stable).T

Optimization terminated successfully.
         Current function value: 0.346368
         Iterations 8
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.081046
         Iterations: 35
Warning: Maximum number of iterations has been exceeded.
         Current function value: inf
         Iterations: 35
Error fitting model: Singular matrix, trying OLS instead

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/local/lib/python3.12/dist-packages/statsmodels/discrete/discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/usr/local/lib/python3.12/dist-packages/statsmodels/discrete/discrete_model.py:2443: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q * linpred)))
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Optimization terminated successfully.
         Current function value: 0.588542
         Iterations 6
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.234536
         Iterations: 35
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.310284
         Iterations: 35
Optimization terminated successfully.
         Current function value: 0.146223
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.118376
         Iterations 8

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

dropped (zero-variance / duplicate): 0

                   auroc        r2  significant  n_hyp  n_dropped
anger           0.709829  0.096884          3.0    9.0        0.0
disgust         0.794579  0.173329          1.0   10.0        0.0
fear            0.817462       NaN          4.0   10.0        0.0
joy             0.724161  0.120810          6.0   10.0        0.0
sadness         0.715175  0.115381          3.0   10.0        0.0
surprise        0.738085  0.154368          2.0   10.0        0.0
curiosity       0.785690  0.252288          2.0   10.0        0.0
disappointment  0.738079  0.085816          1.0   10.0        0.0

## Cosine Annotation

In [7]:
te = get_local_embeddings(held_texts, model=ge.EMBEDDER, nomic_prefix='search_document: ',
                          cache_name='followup_held_doc', batch_size=128)
he = get_local_embeddings(union_hyps, model=ge.EMBEDDER, nomic_prefix='search_query: ',
                          cache_name='followup_hyp_query', batch_size=64)
T = np.stack([te[t] for t in held_texts]).astype(np.float32)
H = np.stack([he[h] for h in union_hyps]).astype(np.float32)
T /= np.linalg.norm(T, axis=1, keepdims=True)
H /= np.linalg.norm(H, axis=1, keepdims=True)
COS = T @ H.T
del te, he, T, H; ge.clear_mem()
COS.shape

Loading embedding chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Loaded 2000 embeddings in 0.6s

Loading embedding chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Loaded 64 embeddings in 0.4s

(2000, 64)

## Cosine vs LLM Agreement

In [8]:
agree = {}
for j, h in enumerate(union_hyps):
    a = llm[h].astype(float)
    if a.std() > 0:
        agree[h] = float(pearsonr(COS[:, j], a)[0])
mean_agreement = float(np.mean(list(agree.values()))) if agree else None
ge.log_json('09_cosine_annotation', {'mean_pearson_cosine_vs_llm': mean_agreement,
                                     'n_compared': len(agree), 'per_hypothesis': agree})
print('hypotheses compared:', len(agree))
print('mean pearson (cosine vs LLM):', mean_agreement)

hypotheses compared: 64
mean pearson (cosine vs LLM): 0.17257118369781074

## Predictiveness Comparison

In [9]:
def separation(a, y):
    p, n = a == 1, a == 0
    return float(y[p].mean() - y[n].mean()) if p.sum() and n.sum() else np.nan

rows = []
for t, neurons in selected.items():
    y = held_targets[t].astype(float)
    for n in neurons:
        h = neuron2hyp.get(n)
        if not h:
            continue
        j = union_hyps.index(h)
        cos_bin = (COS[:, j] >= np.quantile(COS[:, j], 0.9)).astype(int)
        rows.append({'target': t, 'neuron': n, 'hypothesis': h,
                     'llm_sep': separation(llm[h], y),
                     'cos_sep': separation(cos_bin, y)})
cmp_df = pd.DataFrame(rows).dropna(subset=['llm_sep', 'cos_sep'])
rho = float(spearmanr(cmp_df['llm_sep'], cmp_df['cos_sep']).correlation)
ge.log_json('09_cosine_annotation', {'spearman_predictiveness_llm_vs_cosine': rho,
                                     'n_pairs': len(cmp_df),
                                     'comparison': cmp_df.to_dict('records')})
print('spearman(llm_sep, cos_sep) =', round(rho, 3), 'over', len(cmp_df), 'hypotheses')
cmp_df.head(10)

spearman(llm_sep, cos_sep) = 0.404 over 79 hypotheses

,target,neuron,hypothesis,llm_sep,cos_sep
0,anger,350,contains expletive,0.127580,0.035000
1,anger,333,mentions the word 'hate' in the text,0.210842,0.123889
2,anger,944,contains the word 'stupid',0.173989,0.157222
3,anger,722,mentions of 'never',0.108774,0.035000
4,anger,36,"contains a direct command (e.g., 'shut up', 's...",0.219308,0.040556
5,anger,358,contains 'no' in the first position,0.151738,0.096111
6,anger,505,mentions of argument,0.069274,0.007222
7,anger,1005,mentions specific derogatory terms towards people,0.364734,0.140556
8,anger,563,contains the word 'angry',0.109293,0.085000
9,disgust,117,mentions a specific person,-0.020747,0.011111

## Annotator Swap

In [10]:
import importlib.util
from google.colab import userdata
try:
    tok = userdata.get('HF_TOKEN')
    if tok:
        os.environ['HF_TOKEN'] = tok
except Exception:
    pass

# name -> (served model, cache name). Qwen3-1.7B was annotated in notebook 02.
ANNOTATORS = {
    'Qwen3-1.7B': ('Qwen/Qwen3-1.7B', 'goemotions_heldout'),
    'Qwen3-0.6B': ('Qwen/Qwen3-0.6B', 'swap_Qwen3-0.6B'),
}
HAVE_VLLM = importlib.util.find_spec('vllm') is not None
print('vllm available:', HAVE_VLLM, '| free VRAM (GB):', ge.gpu_free_gb())
for name, (model, cname) in ANNOTATORS.items():
    print(f'{name}: {ge.annotation_cache_missing(cname, union_hyps, held_texts)} uncached')
ge.kill_stray_vllm()

vllm available: True | free VRAM (GB): 14.6
Qwen3-1.7B: 0 uncached
Qwen3-0.6B: 0 uncached

In [11]:
# Serve only what is not already cached; cached models cost nothing.
for name, (model, cname) in ANNOTATORS.items():
    missing = ge.annotation_cache_missing(cname, union_hyps, held_texts)
    if not missing:
        print(f'{name}: cached, skipping server')
        continue
    if not HAVE_VLLM:
        print(f'{name}: SKIPPED ({missing} uncached, vllm not installed)')
        continue
    proc = None
    try:
        proc = ge.serve_vllm(model, port=8001, max_model_len=2048,
                             gpu_frac=0.60, enforce_eager=True)
        annotate_texts_with_concepts(texts=held_texts, concepts=union_hyps, model=model,
                                     cache_name=cname, n_workers=16,
                                     max_words_per_example=64, **ge.NO_THINK)
    finally:
        ge.stop_vllm(proc)

Qwen3-1.7B: cached, skipping server
Qwen3-0.6B: cached, skipping server

In [12]:
anns, swap, swap_dropped = {}, {}, {}
for name, (model, cname) in ANNOTATORS.items():
    if ge.annotation_cache_missing(cname, union_hyps, held_texts):
        print(f'{name}: incomplete cache, excluded')
        continue
    a = annotate_texts_with_concepts(texts=held_texts, concepts=union_hyps, model=model,
                                     cache_name=cname, n_workers=1, use_cache_only=True,
                                     uncached_value=0, max_words_per_example=64)
    anns[name] = a
    sig, drops = {}, []
    for t, neurons in selected.items():
        hyps = sorted({neuron2hyp[n] for n in neurons if n in neuron2hyp})
        if len(hyps) < 2:
            continue
        m, df, dropped = ge.score_hypotheses_stable({h: a[h] for h in hyps},
                                                    y_true=held_targets[t].astype(float))
        drops += [dict(d, target=t) for d in dropped]
        if m is not None:
            sig[t] = {'significant': int(m['Significant'][0]),
                      'n_hyp': int(m['Significant'][1]), 'auroc': m.get('auroc')}
    swap[name], swap_dropped[name] = sig, drops
    print(name, '->', {t: v['significant'] for t, v in sig.items()})

Found 128000 cached items; mapped 0 uncached items to 0
Optimization terminated successfully.
         Current function value: 0.346368
         Iterations 8
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.081046
         Iterations: 35
Warning: Maximum number of iterations has been exceeded.
         Current function value: inf
         Iterations: 35
Error fitting model: Singular matrix, trying OLS instead
Optimization terminated successfully.
         Current function value: 0.588542
         Iterations 6

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/local/lib/python3.12/dist-packages/statsmodels/discrete/discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/usr/local/lib/python3.12/dist-packages/statsmodels/discrete/discrete_model.py:2443: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q * linpred)))
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.234536
         Iterations: 35
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.310284
         Iterations: 35
Optimization terminated successfully.
         Current function value: 0.146223
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.118376
         Iterations 8
Qwen3-1.7B -> {'anger': 3, 'disgust': 1, 'fear': 4, 'joy': 6, 'sadness': 3, 'surprise': 2, 'curiosity': 2, 'disappointment': 1}
Found 128000 cached items; mapped 0 uncached items to 0
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.381741
         Iterations: 35
Warning: Maximum number of iterations has been exceeded.
         Current function value: inf
         Iterations: 35
Error fitting model: Singular matrix, trying OLS instead

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/local/lib/python3.12/dist-packages/statsmodels/discrete/discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/usr/local/lib/python3.12/dist-packages/statsmodels/discrete/discrete_model.py:2443: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q * linpred)))
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.071928
         Iterations: 35
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.586545
         Iterations: 35
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.248684
         Iterations: 35
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.347579
         Iterations: 35
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.183931
         Iterations: 35

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/local/lib/python3.12/dist-packages/scipy/stats/_axis_nan_policy.py:579: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/usr/local/lib/python3.12/dist-packages/statsmodels/discrete/discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/usr/local/lib/python3.12/dist-packages/statsmodels/discrete/discrete_model.py:2443: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q * linpred)))

Warning: Maximum number of iterations has been exceeded.
         Current function value: inf
         Iterations: 35
Error fitting model: Singular matrix, trying OLS instead
Qwen3-0.6B -> {'anger': 0, 'disgust': 2, 'fear': 1, 'joy': 5, 'sadness': 1, 'surprise': 4, 'curiosity': 1, 'disappointment': 2}

## Swap Stability

In [13]:
sig_tbl = pd.DataFrame({k: {t: v['significant'] for t, v in s.items()} for k, s in swap.items()})
auc_tbl = pd.DataFrame({k: {t: v['auroc'] for t, v in s.items()} for k, s in swap.items()})

rows = []
names = list(anns)
if len(names) >= 2:
    a1, a2 = anns[names[0]], anns[names[1]]
    for h in union_hyps:
        rows.append({'hypothesis': h,
                     'agreement': float((a1[h] == a2[h]).mean()),
                     f'prev_{names[0]}': float(a1[h].mean()),
                     f'prev_{names[1]}': float(a2[h].mean())})
agree_df = pd.DataFrame(rows)

ge.log_json('10_annotator_swap', {
    'significant_by_model': swap, 'dropped_by_model': swap_dropped,
    'significant_table': sig_tbl.to_dict(), 'auroc_table': auc_tbl.to_dict(),
    'mean_label_agreement': float(agree_df['agreement'].mean()) if len(agree_df) else None,
    'per_hypothesis_agreement': agree_df.to_dict('records')})

if len(agree_df):
    print('mean per-label agreement:', round(agree_df['agreement'].mean(), 3))
print('\nsignificant hypotheses per target:'); print(sig_tbl)
print('\nAUROC:'); print(auc_tbl.round(3))

mean per-label agreement: 0.886

significant hypotheses per target:
                Qwen3-1.7B  Qwen3-0.6B
anger                    3           0
disgust                  1           2
fear                     4           1
joy                      6           5
sadness                  3           1
surprise                 2           4
curiosity                2           1
disappointment           1           2

AUROC:
                Qwen3-1.7B  Qwen3-0.6B
anger                0.710       0.512
disgust              0.795       0.549
fear                 0.817       0.563
joy                  0.724       0.660
sadness              0.715       0.576
surprise             0.738       0.596
curiosity            0.786       0.568
disappointment       0.738       0.529